# Generated by Django 3.2.23 on 2024-01-27 15:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20240127_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True, verbose_name='image'),
        ),
    ]
