# Generated by Django 3.2.23 on 2024-04-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20240407_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='coin_type_max_cap',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
