# Generated by Django 3.2.23 on 2024-04-11 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_coin_type_max_cap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='custom_coin_type',
        ),
    ]
