# Generated by Django 3.2.23 on 2024-04-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_post_coin_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='coin_creator',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
